name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
#   schedule:
#     - cron: 0 */12 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  merge:
    runs-on: Ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [openwrt_18.06,openwrt_21.02]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "3466664+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/dodojie/openwrt-packages.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{matrix.target}}.sh

    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/README/${{matrix.target}}/README.md ] && cp $GITHUB_WORKSPACE/README/${{matrix.target}}/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "同步源码于$(TZ='Asia/Shanghai' date +%Y年%m月%d号-%H点%M分)"
        git push -f --quiet "https://${{ secrets.TOKEN }}@github.com/dodojie/openwrt-packages.git" HEAD:${{matrix.target}}
 

 
